name: build_test_release

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      tag:
        description: 'Tag name'     
        required: true
      note:
        description: 'Release note'
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i -g @vercel/ncc
          npm i @actions/github
          npm run build
      - name: Commit
        run: |
          git config --global user.name 'LCY000'
          git config --global user.email '84628528+LCY000@users.noreply.github.com'
          git commit -am "dist build"
          git push

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
     - uses: actions/checkout@v4
     - name: Test index.js
       env:  
         INPUT_GITHUB_USERNAME: "LCY000"
         INPUT_GITHUB_TOKEN: ${{ ACTION_SECRET_20241011 }}
         INTUT_TARGET_REPOS: '[DevOps-LCY000/activity-log]'
         INPUT_OUTPUT_STYLE: MARKDOWN
         INPUT_IGNORE_EVENTS: '[]'
         INPUT_README_PATH: README.md
         INPUT_COMMIT_MESSAGE: Update README.md
         INPUT_EVENT_LIMIT: '100'
       run: node ./dist/index.js

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest
        run: |
          git config --global user.name 'LCY000'
          git config --global user.email '84628528+LCY000@users.noreply.github.com'
          git pull
      - name: Tag it
        run: |
          git tag -a ${{ inputs.tag }} -m "${{ inputs.note }}"
          git push --tags
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          body: ${{ inputs.note }}
          draft: false
          prerelease: false
